import type { Manner } from "./types";

export type VowelTarget = {
  ipa: string;
  arpabet: string;
  example: string;
  male: [number, number, number];
  female: [number, number, number];
};

/** Hillenbrand / Peterson–Barney style F1–F3 targets (Hz). */
export const VOWEL_TARGETS: VowelTarget[] = [
  { ipa: "i", arpabet: "IY", example: "fleece", male: [270, 2290, 3010], female: [310, 2790, 3310] },
  { ipa: "ɪ", arpabet: "IH", example: "kit", male: [390, 1990, 2550], female: [430, 2480, 3070] },
  { ipa: "ɛ", arpabet: "EH", example: "dress", male: [530, 1840, 2480], female: [610, 2330, 2990] },
  { ipa: "æ", arpabet: "AE", example: "trap", male: [660, 1720, 2410], female: [860, 2050, 2850] },
  { ipa: "ɑ", arpabet: "AA", example: "lot", male: [730, 1090, 2440], female: [850, 1220, 2810] },
  { ipa: "ɔ", arpabet: "AO", example: "thought", male: [570, 840, 2410], female: [590, 920, 2710] },
  { ipa: "ʊ", arpabet: "UH", example: "foot", male: [440, 1020, 2240], female: [470, 1160, 2680] },
  { ipa: "u", arpabet: "UW", example: "goose", male: [300, 870, 2240], female: [370, 950, 2670] },
  { ipa: "ʌ", arpabet: "AH", example: "strut", male: [640, 1190, 2390], female: [760, 1400, 2780] },
  { ipa: "ə", arpabet: "AX", example: "comma", male: [500, 1500, 2500], female: [550, 1640, 2700] },
  { ipa: "ɝ", arpabet: "ER", example: "nurse", male: [490, 1350, 1690], female: [500, 1640, 1960] },
];

export const ARPA_TO_IPA: Record<string, { ipa: string; manner: Manner; example: string }> = {
  IY: { ipa: "i", manner: "vowel", example: "fleece" },
  IH: { ipa: "ɪ", manner: "vowel", example: "kit" },
  EH: { ipa: "ɛ", manner: "vowel", example: "dress" },
  AE: { ipa: "æ", manner: "vowel", example: "trap" },
  AA: { ipa: "ɑ", manner: "vowel", example: "lot" },
  AO: { ipa: "ɔ", manner: "vowel", example: "thought" },
  UH: { ipa: "ʊ", manner: "vowel", example: "foot" },
  UW: { ipa: "u", manner: "vowel", example: "goose" },
  AH: { ipa: "ʌ", manner: "vowel", example: "strut" },
  AX: { ipa: "ə", manner: "vowel", example: "comma" },
  ER: { ipa: "ɝ", manner: "vowel", example: "nurse" },
  EY: { ipa: "eɪ", manner: "diphthong", example: "face" },
  AY: { ipa: "aɪ", manner: "diphthong", example: "price" },
  OY: { ipa: "ɔɪ", manner: "diphthong", example: "choice" },
  OW: { ipa: "oʊ", manner: "diphthong", example: "goat" },
  AW: { ipa: "aʊ", manner: "diphthong", example: "mouth" },
  P: { ipa: "p", manner: "stop", example: "pie" },
  B: { ipa: "b", manner: "stop", example: "buy" },
  T: { ipa: "t", manner: "stop", example: "tie" },
  D: { ipa: "d", manner: "stop", example: "die" },
  K: { ipa: "k", manner: "stop", example: "key" },
  G: { ipa: "g", manner: "stop", example: "guy" },
  CH: { ipa: "tʃ", manner: "affricate", example: "cheap" },
  JH: { ipa: "dʒ", manner: "affricate", example: "jeep" },
  F: { ipa: "f", manner: "fricative", example: "fee" },
  V: { ipa: "v", manner: "fricative", example: "van" },
  TH: { ipa: "θ", manner: "fricative", example: "thin" },
  DH: { ipa: "ð", manner: "fricative", example: "this" },
  S: { ipa: "s", manner: "fricative", example: "see" },
  Z: { ipa: "z", manner: "fricative", example: "zoo" },
  SH: { ipa: "ʃ", manner: "fricative", example: "she" },
  ZH: { ipa: "ʒ", manner: "fricative", example: "vision" },
  HH: { ipa: "h", manner: "fricative", example: "he" },
  M: { ipa: "m", manner: "nasal", example: "me" },
  N: { ipa: "n", manner: "nasal", example: "no" },
  NG: { ipa: "ŋ", manner: "nasal", example: "sing" },
  L: { ipa: "l", manner: "approximant", example: "lee" },
  R: { ipa: "ɹ", manner: "approximant", example: "read" },
  W: { ipa: "w", manner: "approximant", example: "we" },
  Y: { ipa: "j", manner: "approximant", example: "yes" },
};

/** Compact CMU-style dictionary for alignment. ARPAbet, no stress digits. */
export const CMU: Record<string, string[]> = {
  a: ["AH"],
  about: ["AH", "B", "AW", "T"],
  after: ["AE", "F", "T", "ER"],
  all: ["AO", "L"],
  also: ["AO", "L", "S", "OW"],
  an: ["AE", "N"],
  and: ["AH", "N", "D"],
  any: ["EH", "N", "IY"],
  are: ["AA", "R"],
  as: ["AE", "Z"],
  at: ["AE", "T"],
  back: ["B", "AE", "K"],
  be: ["B", "IY"],
  because: ["B", "IH", "K", "AO", "Z"],
  been: ["B", "IH", "N"],
  but: ["B", "AH", "T"],
  by: ["B", "AY"],
  can: ["K", "AE", "N"],
  cat: ["K", "AE", "T"],
  come: ["K", "AH", "M"],
  could: ["K", "UH", "D"],
  day: ["D", "EY"],
  did: ["D", "IH", "D"],
  do: ["D", "UW"],
  even: ["IY", "V", "IH", "N"],
  first: ["F", "ER", "S", "T"],
  for: ["F", "AO", "R"],
  from: ["F", "R", "AH", "M"],
  get: ["G", "EH", "T"],
  go: ["G", "OW"],
  good: ["G", "UH", "D"],
  had: ["HH", "AE", "D"],
  has: ["HH", "AE", "Z"],
  have: ["HH", "AE", "V"],
  he: ["HH", "IY"],
  hello: ["HH", "AH", "L", "OW"],
  her: ["HH", "ER"],
  here: ["HH", "IY", "R"],
  him: ["HH", "IH", "M"],
  his: ["HH", "IH", "Z"],
  how: ["HH", "AW"],
  i: ["AY"],
  if: ["IH", "F"],
  in: ["IH", "N"],
  into: ["IH", "N", "T", "UW"],
  is: ["IH", "Z"],
  it: ["IH", "T"],
  its: ["IH", "T", "S"],
  just: ["JH", "AH", "S", "T"],
  know: ["N", "OW"],
  like: ["L", "AY", "K"],
  look: ["L", "UH", "K"],
  make: ["M", "EY", "K"],
  me: ["M", "IY"],
  more: ["M", "AO", "R"],
  my: ["M", "AY"],
  new: ["N", "UW"],
  no: ["N", "OW"],
  not: ["N", "AA", "T"],
  now: ["N", "AW"],
  of: ["AH", "V"],
  on: ["AA", "N"],
  one: ["W", "AH", "N"],
  only: ["OW", "N", "L", "IY"],
  or: ["AO", "R"],
  other: ["AH", "DH", "ER"],
  our: ["AW", "ER"],
  out: ["AW", "T"],
  over: ["OW", "V", "ER"],
  people: ["P", "IY", "P", "AH", "L"],
  rain: ["R", "EY", "N"],
  said: ["S", "EH", "D"],
  see: ["S", "IY"],
  sells: ["S", "EH", "L", "Z"],
  she: ["SH", "IY"],
  sit: ["S", "IH", "T"],
  so: ["S", "OW"],
  some: ["S", "AH", "M"],
  spain: ["S", "P", "EY", "N"],
  take: ["T", "EY", "K"],
  than: ["DH", "AE", "N"],
  that: ["DH", "AE", "T"],
  the: ["DH", "AH"],
  their: ["DH", "EH", "R"],
  them: ["DH", "EH", "M"],
  then: ["DH", "EH", "N"],
  there: ["DH", "EH", "R"],
  these: ["DH", "IY", "Z"],
  they: ["DH", "EY"],
  this: ["DH", "IH", "S"],
  time: ["T", "AY", "M"],
  to: ["T", "UW"],
  two: ["T", "UW"],
  up: ["AH", "P"],
  us: ["AH", "S"],
  very: ["V", "EH", "R", "IY"],
  voice: ["V", "OY", "S"],
  want: ["W", "AA", "N", "T"],
  was: ["W", "AH", "Z"],
  we: ["W", "IY"],
  well: ["W", "EH", "L"],
  were: ["W", "ER"],
  what: ["W", "AH", "T"],
  when: ["W", "EH", "N"],
  which: ["W", "IH", "CH"],
  who: ["HH", "UW"],
  will: ["W", "IH", "L"],
  with: ["W", "IH", "DH"],
  world: ["W", "ER", "L", "D"],
  would: ["W", "UH", "D"],
  yes: ["Y", "EH", "S"],
  you: ["Y", "UW"],
  your: ["Y", "AO", "R"],
};

export const MANNER_DURATION: Record<Manner, number> = {
  vowel: 1.4,
  diphthong: 1.7,
  stop: 0.7,
  fricative: 1.0,
  nasal: 0.9,
  approximant: 0.85,
  affricate: 0.95,
  silence: 0.5,
};

export function nearestVowel(f1: number, f2: number, feminineBias: number) {
  let best = VOWEL_TARGETS[0]!;
  let bestD = Infinity;
  for (const v of VOWEL_TARGETS) {
    const t1 = v.male[0] * (1 - feminineBias) + v.female[0] * feminineBias;
    const t2 = v.male[1] * (1 - feminineBias) + v.female[1] * feminineBias;
    const d = ((f1 - t1) / 400) ** 2 + ((f2 - t2) / 800) ** 2;
    if (d < bestD) {
      bestD = d;
      best = v;
    }
  }
  const confidence = Math.max(0.25, 1 - Math.sqrt(bestD) * 0.7);
  return { vowel: best, confidence, distance: bestD };
}
